### PR TITLE
removed verifyuser export and added error statuses to routes

### PR DESCRIPTION
**Pull request by pacqu**
- Corrected module exports for verify.js to remove now deleted verifyUser function
- Added Error Statuses to Routes (per Steven's request)
- Changed logic for routes (i.e. login route) such that if user isn't found, it's reported back to user in status code

### CODE REVIEW

**Review by kaizenc — APPROVED** [review]
lgtm, just wondering if it's possible to send the error message alongside the status?

**Comment by pacqu** [comment]
@kaizenc There should be a way to do it, I tried to do it before but it was giving me issues. I'll try it again.

**Comment by kaizenc** [comment]
if you can't/it's too difficult, dwai just merge in the pr

**Comment by pacqu** [comment]
*whips* you woulda thot

**Pull request merged**
